#	$OpenBSD: Makefile,v 1.2 2009/08/08 19:37:14 sobrado Exp $
#	$NetBSD: Makefile,v 1.11 2003/08/01 17:04:04 lukem Exp $

PROG=		mklocale
SRCS=		yacc.y lex.l
#CPPFLAGS+=	-I. -I${.CURDIR} -I${.CURDIR}/../../lib/libc/locale -I${.CURDIR}/../../lib/libc/include
CPPFLAGS+=	-I. -I${.CURDIR} -I${.CURDIR}/../../lib/libc/locale

.include <bsd.prog.mk>
