#define PCC_MAJOR 0
#define PCC_MINOR 9
#define PCC_MINORMINOR 9
#define	PACKAGE_VERSION "0.9.9"
#define VERSSTR "pcc " PACKAGE_VERSION
#define	PACKAGE_STRING	VERSSTR
#define	TARGOS OpenBSD

#define YYTEXT_POINTER 1
#define	HAVE_CPP_VARARG_MACRO_GCC
