.PATH: ${.CURDIR}/src

LIB=		cxxrt

SRCS+=		libelftc_dem_gnu3.c\
		terminate.cc\
		dynamic_cast.cc\
		memory.cc\
		auxhelper.cc\
		exception.cc\
		stdexcept.cc\
		typeinfo.cc\
		guard.cc

CXXFLAGS+=	-I${SRCDIR}

.include <bsd.lib.mk>
